/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUzytkownicyRouteImport } from './routes/_authenticated/uzytkownicy'
import { Route as AuthenticatedUstawieniaRouteImport } from './routes/_authenticated/ustawienia'
import { Route as AuthenticatedSprzedazRouteImport } from './routes/_authenticated/sprzedaz'
import { Route as AuthenticatedRozliczeniaRouteImport } from './routes/_authenticated/rozliczenia'
import { Route as AuthenticatedRaportyRouteImport } from './routes/_authenticated/raporty'
import { Route as AuthenticatedPrzewoznicyRouteImport } from './routes/_authenticated/przewoznicy'
import { Route as AuthenticatedPowiadomieniaRouteImport } from './routes/_authenticated/powiadomienia'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedMagazynRouteImport } from './routes/_authenticated/magazyn'
import { Route as AuthenticatedLogistykaRouteImport } from './routes/_authenticated/logistyka'
import { Route as AuthenticatedKlienciRouteImport } from './routes/_authenticated/klienci'
import { Route as AuthenticatedFakturowanieRouteImport } from './routes/_authenticated/fakturowanie'
import { Route as AuthenticatedDostawyRouteImport } from './routes/_authenticated/dostawy'
import { Route as AuthenticatedDostawcyRouteImport } from './routes/_authenticated/dostawcy'
import { Route as AuthenticatedDostawyIndexRouteImport } from './routes/_authenticated/dostawy.index'
import { Route as AuthenticatedDostawyNowaRouteImport } from './routes/_authenticated/dostawy.nowa'
import { Route as AuthenticatedDostawyIdRouteImport } from './routes/_authenticated/dostawy.$id'
import { Route as AuthenticatedDostawyIdEdytujRouteImport } from './routes/_authenticated/dostawy.$id.edytuj'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUzytkownicyRoute =
  AuthenticatedUzytkownicyRouteImport.update({
    id: '/uzytkownicy',
    path: '/uzytkownicy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUstawieniaRoute = AuthenticatedUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSprzedazRoute = AuthenticatedSprzedazRouteImport.update({
  id: '/sprzedaz',
  path: '/sprzedaz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRozliczeniaRoute =
  AuthenticatedRozliczeniaRouteImport.update({
    id: '/rozliczenia',
    path: '/rozliczenia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRaportyRoute = AuthenticatedRaportyRouteImport.update({
  id: '/raporty',
  path: '/raporty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrzewoznicyRoute =
  AuthenticatedPrzewoznicyRouteImport.update({
    id: '/przewoznicy',
    path: '/przewoznicy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPowiadomieniaRoute =
  AuthenticatedPowiadomieniaRouteImport.update({
    id: '/powiadomienia',
    path: '/powiadomienia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMagazynRoute = AuthenticatedMagazynRouteImport.update({
  id: '/magazyn',
  path: '/magazyn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogistykaRoute = AuthenticatedLogistykaRouteImport.update({
  id: '/logistyka',
  path: '/logistyka',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKlienciRoute = AuthenticatedKlienciRouteImport.update({
  id: '/klienci',
  path: '/klienci',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFakturowanieRoute =
  AuthenticatedFakturowanieRouteImport.update({
    id: '/fakturowanie',
    path: '/fakturowanie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDostawyRoute = AuthenticatedDostawyRouteImport.update({
  id: '/dostawy',
  path: '/dostawy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDostawcyRoute = AuthenticatedDostawcyRouteImport.update({
  id: '/dostawcy',
  path: '/dostawcy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDostawyIndexRoute =
  AuthenticatedDostawyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDostawyRoute,
  } as any)
const AuthenticatedDostawyNowaRoute =
  AuthenticatedDostawyNowaRouteImport.update({
    id: '/nowa',
    path: '/nowa',
    getParentRoute: () => AuthenticatedDostawyRoute,
  } as any)
const AuthenticatedDostawyIdRoute = AuthenticatedDostawyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDostawyRoute,
} as any)
const AuthenticatedDostawyIdEdytujRoute =
  AuthenticatedDostawyIdEdytujRouteImport.update({
    id: '/edytuj',
    path: '/edytuj',
    getParentRoute: () => AuthenticatedDostawyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dostawcy': typeof AuthenticatedDostawcyRoute
  '/dostawy': typeof AuthenticatedDostawyRouteWithChildren
  '/fakturowanie': typeof AuthenticatedFakturowanieRoute
  '/klienci': typeof AuthenticatedKlienciRoute
  '/logistyka': typeof AuthenticatedLogistykaRoute
  '/magazyn': typeof AuthenticatedMagazynRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/powiadomienia': typeof AuthenticatedPowiadomieniaRoute
  '/przewoznicy': typeof AuthenticatedPrzewoznicyRoute
  '/raporty': typeof AuthenticatedRaportyRoute
  '/rozliczenia': typeof AuthenticatedRozliczeniaRoute
  '/sprzedaz': typeof AuthenticatedSprzedazRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/uzytkownicy': typeof AuthenticatedUzytkownicyRoute
  '/dostawy/$id': typeof AuthenticatedDostawyIdRouteWithChildren
  '/dostawy/nowa': typeof AuthenticatedDostawyNowaRoute
  '/dostawy/': typeof AuthenticatedDostawyIndexRoute
  '/dostawy/$id/edytuj': typeof AuthenticatedDostawyIdEdytujRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dostawcy': typeof AuthenticatedDostawcyRoute
  '/fakturowanie': typeof AuthenticatedFakturowanieRoute
  '/klienci': typeof AuthenticatedKlienciRoute
  '/logistyka': typeof AuthenticatedLogistykaRoute
  '/magazyn': typeof AuthenticatedMagazynRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/powiadomienia': typeof AuthenticatedPowiadomieniaRoute
  '/przewoznicy': typeof AuthenticatedPrzewoznicyRoute
  '/raporty': typeof AuthenticatedRaportyRoute
  '/rozliczenia': typeof AuthenticatedRozliczeniaRoute
  '/sprzedaz': typeof AuthenticatedSprzedazRoute
  '/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/uzytkownicy': typeof AuthenticatedUzytkownicyRoute
  '/dostawy/$id': typeof AuthenticatedDostawyIdRouteWithChildren
  '/dostawy/nowa': typeof AuthenticatedDostawyNowaRoute
  '/dostawy': typeof AuthenticatedDostawyIndexRoute
  '/dostawy/$id/edytuj': typeof AuthenticatedDostawyIdEdytujRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dostawcy': typeof AuthenticatedDostawcyRoute
  '/_authenticated/dostawy': typeof AuthenticatedDostawyRouteWithChildren
  '/_authenticated/fakturowanie': typeof AuthenticatedFakturowanieRoute
  '/_authenticated/klienci': typeof AuthenticatedKlienciRoute
  '/_authenticated/logistyka': typeof AuthenticatedLogistykaRoute
  '/_authenticated/magazyn': typeof AuthenticatedMagazynRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/powiadomienia': typeof AuthenticatedPowiadomieniaRoute
  '/_authenticated/przewoznicy': typeof AuthenticatedPrzewoznicyRoute
  '/_authenticated/raporty': typeof AuthenticatedRaportyRoute
  '/_authenticated/rozliczenia': typeof AuthenticatedRozliczeniaRoute
  '/_authenticated/sprzedaz': typeof AuthenticatedSprzedazRoute
  '/_authenticated/ustawienia': typeof AuthenticatedUstawieniaRoute
  '/_authenticated/uzytkownicy': typeof AuthenticatedUzytkownicyRoute
  '/_authenticated/dostawy/$id': typeof AuthenticatedDostawyIdRouteWithChildren
  '/_authenticated/dostawy/nowa': typeof AuthenticatedDostawyNowaRoute
  '/_authenticated/dostawy/': typeof AuthenticatedDostawyIndexRoute
  '/_authenticated/dostawy/$id/edytuj': typeof AuthenticatedDostawyIdEdytujRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dostawcy'
    | '/dostawy'
    | '/fakturowanie'
    | '/klienci'
    | '/logistyka'
    | '/magazyn'
    | '/panel'
    | '/powiadomienia'
    | '/przewoznicy'
    | '/raporty'
    | '/rozliczenia'
    | '/sprzedaz'
    | '/ustawienia'
    | '/uzytkownicy'
    | '/dostawy/$id'
    | '/dostawy/nowa'
    | '/dostawy/'
    | '/dostawy/$id/edytuj'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dostawcy'
    | '/fakturowanie'
    | '/klienci'
    | '/logistyka'
    | '/magazyn'
    | '/panel'
    | '/powiadomienia'
    | '/przewoznicy'
    | '/raporty'
    | '/rozliczenia'
    | '/sprzedaz'
    | '/ustawienia'
    | '/uzytkownicy'
    | '/dostawy/$id'
    | '/dostawy/nowa'
    | '/dostawy'
    | '/dostawy/$id/edytuj'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dostawcy'
    | '/_authenticated/dostawy'
    | '/_authenticated/fakturowanie'
    | '/_authenticated/klienci'
    | '/_authenticated/logistyka'
    | '/_authenticated/magazyn'
    | '/_authenticated/panel'
    | '/_authenticated/powiadomienia'
    | '/_authenticated/przewoznicy'
    | '/_authenticated/raporty'
    | '/_authenticated/rozliczenia'
    | '/_authenticated/sprzedaz'
    | '/_authenticated/ustawienia'
    | '/_authenticated/uzytkownicy'
    | '/_authenticated/dostawy/$id'
    | '/_authenticated/dostawy/nowa'
    | '/_authenticated/dostawy/'
    | '/_authenticated/dostawy/$id/edytuj'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/uzytkownicy': {
      id: '/_authenticated/uzytkownicy'
      path: '/uzytkownicy'
      fullPath: '/uzytkownicy'
      preLoaderRoute: typeof AuthenticatedUzytkownicyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ustawienia': {
      id: '/_authenticated/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof AuthenticatedUstawieniaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprzedaz': {
      id: '/_authenticated/sprzedaz'
      path: '/sprzedaz'
      fullPath: '/sprzedaz'
      preLoaderRoute: typeof AuthenticatedSprzedazRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rozliczenia': {
      id: '/_authenticated/rozliczenia'
      path: '/rozliczenia'
      fullPath: '/rozliczenia'
      preLoaderRoute: typeof AuthenticatedRozliczeniaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raporty': {
      id: '/_authenticated/raporty'
      path: '/raporty'
      fullPath: '/raporty'
      preLoaderRoute: typeof AuthenticatedRaportyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/przewoznicy': {
      id: '/_authenticated/przewoznicy'
      path: '/przewoznicy'
      fullPath: '/przewoznicy'
      preLoaderRoute: typeof AuthenticatedPrzewoznicyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/powiadomienia': {
      id: '/_authenticated/powiadomienia'
      path: '/powiadomienia'
      fullPath: '/powiadomienia'
      preLoaderRoute: typeof AuthenticatedPowiadomieniaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/magazyn': {
      id: '/_authenticated/magazyn'
      path: '/magazyn'
      fullPath: '/magazyn'
      preLoaderRoute: typeof AuthenticatedMagazynRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistyka': {
      id: '/_authenticated/logistyka'
      path: '/logistyka'
      fullPath: '/logistyka'
      preLoaderRoute: typeof AuthenticatedLogistykaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/klienci': {
      id: '/_authenticated/klienci'
      path: '/klienci'
      fullPath: '/klienci'
      preLoaderRoute: typeof AuthenticatedKlienciRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fakturowanie': {
      id: '/_authenticated/fakturowanie'
      path: '/fakturowanie'
      fullPath: '/fakturowanie'
      preLoaderRoute: typeof AuthenticatedFakturowanieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dostawy': {
      id: '/_authenticated/dostawy'
      path: '/dostawy'
      fullPath: '/dostawy'
      preLoaderRoute: typeof AuthenticatedDostawyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dostawcy': {
      id: '/_authenticated/dostawcy'
      path: '/dostawcy'
      fullPath: '/dostawcy'
      preLoaderRoute: typeof AuthenticatedDostawcyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dostawy/': {
      id: '/_authenticated/dostawy/'
      path: '/'
      fullPath: '/dostawy/'
      preLoaderRoute: typeof AuthenticatedDostawyIndexRouteImport
      parentRoute: typeof AuthenticatedDostawyRoute
    }
    '/_authenticated/dostawy/nowa': {
      id: '/_authenticated/dostawy/nowa'
      path: '/nowa'
      fullPath: '/dostawy/nowa'
      preLoaderRoute: typeof AuthenticatedDostawyNowaRouteImport
      parentRoute: typeof AuthenticatedDostawyRoute
    }
    '/_authenticated/dostawy/$id': {
      id: '/_authenticated/dostawy/$id'
      path: '/$id'
      fullPath: '/dostawy/$id'
      preLoaderRoute: typeof AuthenticatedDostawyIdRouteImport
      parentRoute: typeof AuthenticatedDostawyRoute
    }
    '/_authenticated/dostawy/$id/edytuj': {
      id: '/_authenticated/dostawy/$id/edytuj'
      path: '/edytuj'
      fullPath: '/dostawy/$id/edytuj'
      preLoaderRoute: typeof AuthenticatedDostawyIdEdytujRouteImport
      parentRoute: typeof AuthenticatedDostawyIdRoute
    }
  }
}

interface AuthenticatedDostawyIdRouteChildren {
  AuthenticatedDostawyIdEdytujRoute: typeof AuthenticatedDostawyIdEdytujRoute
}

const AuthenticatedDostawyIdRouteChildren: AuthenticatedDostawyIdRouteChildren =
  {
    AuthenticatedDostawyIdEdytujRoute: AuthenticatedDostawyIdEdytujRoute,
  }

const AuthenticatedDostawyIdRouteWithChildren =
  AuthenticatedDostawyIdRoute._addFileChildren(
    AuthenticatedDostawyIdRouteChildren,
  )

interface AuthenticatedDostawyRouteChildren {
  AuthenticatedDostawyIdRoute: typeof AuthenticatedDostawyIdRouteWithChildren
  AuthenticatedDostawyNowaRoute: typeof AuthenticatedDostawyNowaRoute
  AuthenticatedDostawyIndexRoute: typeof AuthenticatedDostawyIndexRoute
}

const AuthenticatedDostawyRouteChildren: AuthenticatedDostawyRouteChildren = {
  AuthenticatedDostawyIdRoute: AuthenticatedDostawyIdRouteWithChildren,
  AuthenticatedDostawyNowaRoute: AuthenticatedDostawyNowaRoute,
  AuthenticatedDostawyIndexRoute: AuthenticatedDostawyIndexRoute,
}

const AuthenticatedDostawyRouteWithChildren =
  AuthenticatedDostawyRoute._addFileChildren(AuthenticatedDostawyRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDostawcyRoute: typeof AuthenticatedDostawcyRoute
  AuthenticatedDostawyRoute: typeof AuthenticatedDostawyRouteWithChildren
  AuthenticatedFakturowanieRoute: typeof AuthenticatedFakturowanieRoute
  AuthenticatedKlienciRoute: typeof AuthenticatedKlienciRoute
  AuthenticatedLogistykaRoute: typeof AuthenticatedLogistykaRoute
  AuthenticatedMagazynRoute: typeof AuthenticatedMagazynRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPowiadomieniaRoute: typeof AuthenticatedPowiadomieniaRoute
  AuthenticatedPrzewoznicyRoute: typeof AuthenticatedPrzewoznicyRoute
  AuthenticatedRaportyRoute: typeof AuthenticatedRaportyRoute
  AuthenticatedRozliczeniaRoute: typeof AuthenticatedRozliczeniaRoute
  AuthenticatedSprzedazRoute: typeof AuthenticatedSprzedazRoute
  AuthenticatedUstawieniaRoute: typeof AuthenticatedUstawieniaRoute
  AuthenticatedUzytkownicyRoute: typeof AuthenticatedUzytkownicyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDostawcyRoute: AuthenticatedDostawcyRoute,
  AuthenticatedDostawyRoute: AuthenticatedDostawyRouteWithChildren,
  AuthenticatedFakturowanieRoute: AuthenticatedFakturowanieRoute,
  AuthenticatedKlienciRoute: AuthenticatedKlienciRoute,
  AuthenticatedLogistykaRoute: AuthenticatedLogistykaRoute,
  AuthenticatedMagazynRoute: AuthenticatedMagazynRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPowiadomieniaRoute: AuthenticatedPowiadomieniaRoute,
  AuthenticatedPrzewoznicyRoute: AuthenticatedPrzewoznicyRoute,
  AuthenticatedRaportyRoute: AuthenticatedRaportyRoute,
  AuthenticatedRozliczeniaRoute: AuthenticatedRozliczeniaRoute,
  AuthenticatedSprzedazRoute: AuthenticatedSprzedazRoute,
  AuthenticatedUstawieniaRoute: AuthenticatedUstawieniaRoute,
  AuthenticatedUzytkownicyRoute: AuthenticatedUzytkownicyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
